### ISSUE TITLE
Defuse bad-words filters by adding a white list

### ISSUE THREAD

**Issue by wp99cp** [cevi/logo-generator#11]
I absolutely understand why a bad-word filter has been included in the logo generator. However, this filter is too restrictive for certain words. For example, the word "Marschzeittabelle" is censored since it contains "arsch". It would be useful to add a white list such that certain brave words will not be censored.

**Possible words for such a white list:**
Marschzeit, Marschtabelle, ...

Those words would be useful to create claims for the new [Walk-Time Table Generator](https://github.com/cevi/automatic_walk-time_tables).

For those who are interested, right now the following words are included in the filter:
https://github.com/cevi/logo-generator/blob/7a0a59bdd74095e83cdb63ea5cc72567233acaee/src/js/Components/Logo/index.js#L376-L407

**Comment by btemperli** [comment]
Hi @wp99cp 

Thank you for this issue and the wish to whitelisting some words.
I added now a whitelist-function with the word **MARSCH**, that should fix your problems with the walk-time generator.

Do you need more words on the list? Or do you want to change the existing black-list? Please add a comment. Otherwise, if everything works for you as excepted, you can close the issue.

**Comment by wp99cp** [comment]
Works as excepted now, thank you very much!
